import type { IssueCardItem } from '@/types/issue'

export const LANDING_DEMO_ISSUES: IssueCardItem[] = [
    {
        number: 12931,
        title: 'Fix stale closure in useEffect cleanup warning',
        url: 'https://github.com/facebook/react/issues/12931',
        repoFullName: 'facebook/react',
        repoUrl: 'https://github.com/facebook/react',
        language: 'TypeScript',
        stargazerCount: 231_000,
        labels: ['good first issue'],
        commentCount: 3,
        body: 'The cleanup function in this effect closes over a stale value of `count`, so the warning fires even after the dependency array is fixed. We should recompute it inside the effect instead.',
        createdAt: new Date(Date.now() - 6 * 86_400_000).toISOString(),
        updatedAt: new Date(Date.now() - 86_400_000).toISOString(),
        score: 85,
        difficultyLevel: 'beginner',
        contributionType: 'bug',
        competitionLevel: 'OPEN',
        hasPR: false,
        repoActivityLevel: 'active',
    },
    {
        number: 8420,
        title: 'Improve HMR error overlay message for CSS modules',
        url: 'https://github.com/vitejs/vite/issues/8420',
        repoFullName: 'vitejs/vite',
        repoUrl: 'https://github.com/vitejs/vite',
        language: 'JavaScript',
        stargazerCount: 68_000,
        labels: ['documentation'],
        commentCount: 1,
        body: 'When a CSS module fails to parse, the overlay only prints "unknown error" with no file path.',
        createdAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
        score: 74,
        difficultyLevel: 'junior',
        contributionType: 'doc',
        competitionLevel: 'OPEN',
        hasPR: false,
        repoActivityLevel: 'active',
    },
    {
        number: 5190,
        title: 'docs: clarify RLS policy example in quickstart guide',
        url: 'https://github.com/supabase/supabase/issues/5190',
        repoFullName: 'supabase/supabase',
        repoUrl: 'https://github.com/supabase/supabase',
        language: 'TypeScript',
        stargazerCount: 74_000,
        labels: ['good first issue'],
        commentCount: 0,
        body: 'The quickstart guide shows a policy that references `auth.uid()` but never explains what happens for anonymous requests, which confused a couple of people in Discord.',
        createdAt: new Date(Date.now() - 9 * 86_400_000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
        score: 68,
        difficultyLevel: 'beginner',
        contributionType: 'doc',
        competitionLevel: 'HAS_PR',
        hasPR: true,
        repoActivityLevel: 'moderate',
    },
    {
        number: 24177,
        title: 'fix: normalize Windows path separators in std/path',
        url: 'https://github.com/denoland/deno/issues/24177',
        repoFullName: 'denoland/deno',
        repoUrl: 'https://github.com/denoland/deno',
        language: 'Rust',
        stargazerCount: 95_000,
        labels: ['good first issue'],
        commentCount: 4,
        body: 'join() returns backslashes on Windows even when the caller explicitly asked for a POSIX-style path.',
        createdAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 86_400_000).toISOString(),
        score: 61,
        difficultyLevel: 'mid',
        contributionType: 'bug',
        competitionLevel: 'OPEN',
        hasPR: false,
        repoActivityLevel: 'active',
    },
]

export async function noopToggleBookmark() {}
